### PR TITLE
[Issue #72] ParallelIce_py and Windows

### PR DESCRIPTION
**Pull request by aitormf**
This PR adds  ParallelIce_py (Issue #72) to all python exercices less 3D Reconstruction because this use 3d Viewer and it doesn't run in Windows.

in Windows we already use Ice 3.6 because it was very difficult to install 3.5 and will soon jump to Ice 3.6

## Instalation in Windows: 

**1. Download Dependences:**

Download python 2.7.12 and install checked env variables (Is posible that you need restart to run the PATH):  
https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi 
 
Download qt 4.8.7:  
http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-vs2010-4.8.7.exe 

Download github Desktop:
https://desktop.github.com/
 
update pip: 
<pre>python -m pip install --upgrade pip </pre>
Install deps:
<pre>pip install numpy zeroc-ice 
pip install http://jderobot.org/store/aitormf/uploads/windows/opencv_python-3.1.0-cp27-cp27m-win_amd64.whl 
pip install http://jderobot.org/store/aitormf/uploads/windows/PyQt4-4.11.4-cp27-none-win_amd64.whl 
pip install http://jderobot.org/store/aitormf/uploads/windows/PyQwt-5.2.1-cp27-none-win_amd64.whl 
</pre>

**2. Install JdeRobot Python by Pip:**
<pre>pip install  http://jderobot.org/store/aitormf/uploads/windows/JdeRobot-0.1.0-py2-none-any.whl </pre>

**3. Download TeachingRobotics**
With git Shell clone the repository as in Linux and run the exercices with CMD o powershell

<pre>git clone -b paralellice https://github.com/aitormf/TeachingRobotics.git</pre>

## Using Docker for gazebo

1. Download docker: [http://www.docker.com/products/docker](http://www.docker.com/products/docker)

2. Donwload Kitematic of docker

3. Run Kinematic and press "docker cli" button

4. Download and run the image [aitormf/jderobot:gzweb](https://hub.docker.com/r/aitormf/jderobot/tags/) putting (Changing **world_name** by the world):
<pre>
docker run -tiP --rm -p 7681:7681 aitormf/jderobot:gzweb world world_name
</pre>

In following video you can see a example:

[Introrob py + GzWeb in Windows](http://www.youtube.com/watch?v=v00TCr-aSWM)

## Test  specific configurations to exercises

you have to run the exercise docker image instead of   jderobot:gzweb image.

I haver prepared two examples, follow_line and follow_road:

<pre>
docker run -tiP --rm -p 7681:7681 aitormf/teachingrobotics:follow_line
</pre>

<pre>
docker run -tiP --rm -p 7681:7681 aitormf/teachingrobotics:follow_road
</pre>

## Dockerfiles

you can see the dockerfiles in t[his github repository](https://github.com/aitormf/docker-jderobot)

### CODE REVIEW

**Comment by fqez** [comment]
Hi Aitor, you maybe should create an entry in the wiki with those instructions. So it can be reached whenever this PR is merged.

**Comment by aitormf** [comment]
I have thought about doing it, but the part of the docker is not yet ready. These instructions are a first approximation so you can try it in windows.

I'm doing last versions of Dockers now. When I finish and Docker works well I will put the finally version of this instructions in the wiki.

**Comment by fqez** [comment]
Can we use powershell to run the commands?

**Comment by aitormf** [comment]
In principle Yes. Not should have no problem

**Comment by fqez** [comment]
Could you extend the instructions so they show how to configure/install docker, and how to download your docker repo for all those users (like me) that doesn't know how this works? It would be so useful!

**Comment by fqez** [comment]
Tested and working. The only thing is a bug that avoid gzweb GUI to be shown. @aitormf can you extend the info about this issue?

**Comment by aitormf** [comment]
updated first post with more instructions about docker and new video

**Comment by aitormf** [comment]
updated first post with examples with preconfigured worlds for practices so you say it's better thinking about the exercises, use images that are preconfigured with a world or launch the world specific from jderobot:gzweb.

These preconfigured  images depends on jderobot:gzweb adding the world

**Pull request merged**
